/**
 * Fetch real stroke order SVG paths from KanjiVG for all 1,026 education kanji.
 * Outputs src/data/strokes.ts with StrokeData entries.
 *
 * Usage: node scripts/fetch-strokes.mjs
 */

import { readFileSync } from 'fs';
import { writeFileSync } from 'fs';
import path from 'path';

// Load all kanji characters from grade data files
const GRADES = [1, 2, 3, 4, 5, 6];
const allKanji = [];

for (const grade of GRADES) {
  const filePath = path.join(process.cwd(), `src/data/kanji/grade${grade}.ts`);
  const content = readFileSync(filePath, 'utf8');
  // Extract character fields
  const matches = content.matchAll(/character:\s*'([^']+)'/g);
  for (const m of matches) {
    allKanji.push(m[1]);
  }
}

console.log(`Found ${allKanji.length} kanji to fetch stroke data for.`);

const BASE_URL = 'https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/';

async function fetchStrokePaths(char) {
  const codepoint = char.codePointAt(0).toString(16).padStart(5, '0');
  const url = `${BASE_URL}${codepoint}.svg`;

  try {
    const resp = await fetch(url);
    if (!resp.ok) return null;
    const svg = await resp.text();

    // Extract all path d attributes in order
    const paths = [];
    const regex = /\bd="([^"]+)"/g;
    let match;
    while ((match = regex.exec(svg)) !== null) {
      // Skip non-stroke paths (e.g. clip paths)
      if (match[1].includes('M') && !match[1].startsWith('0')) {
        paths.push(match[1]);
      }
    }
    return paths.length > 0 ? paths : null;
  } catch {
    return null;
  }
}

async function main() {
  const results = [];
  let success = 0;
  let fail = 0;

  // Process in batches of 10 to avoid rate limiting
  for (let i = 0; i < allKanji.length; i += 10) {
    const batch = allKanji.slice(i, i + 10);
    const promises = batch.map(async (char, idx) => {
      const kanjiIndex = i + idx;
      const paths = await fetchStrokePaths(char);
      if (paths) {
        success++;
        results.push({ id: kanjiIndex + 1, character: char, paths });
      } else {
        fail++;
        console.log(`  MISS: ${char} (${kanjiIndex + 1})`);
      }
    });
    await Promise.all(promises);

    if ((i + 10) % 100 === 0 || i + 10 >= allKanji.length) {
      console.log(`Progress: ${Math.min(i + 10, allKanji.length)}/${allKanji.length} (${success} ok, ${fail} miss)`);
    }
  }

  // Sort by ID
  results.sort((a, b) => a.id - b.id);

  // Generate TypeScript file
  let ts = `/**
 * Real stroke order SVG paths from KanjiVG (https://kanjivg.tagaini.net/)
 * Licensed under Creative Commons Attribution-Share Alike 3.0
 * Auto-generated by scripts/fetch-strokes.mjs
 *
 * Total: ${results.length} kanji with stroke data
 */

export interface StrokeEntry {
  kanjiId: number;
  character: string;
  paths: string[];
  viewBox: string;
}

export const STROKE_DATA: StrokeEntry[] = [\n`;

  for (const r of results) {
    const pathsStr = r.paths.map((p) => `      '${p.replace(/'/g, "\\'")}'`).join(',\n');
    ts += `  {\n    kanjiId: ${r.id},\n    character: '${r.character}',\n    viewBox: '0 0 109 109',\n    paths: [\n${pathsStr}\n    ],\n  },\n`;
  }

  ts += '];\n';

  const outPath = path.join(process.cwd(), 'src/data/strokes.ts');
  writeFileSync(outPath, ts);
  console.log(`\nDone! Wrote ${results.length} entries to ${outPath}`);
}

main();
